# This is a basic workflow to help you get started with Actions

name: Doxygen-Auto-Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Doxygenize
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@7410df330cf5ede72291d768e2e051c44181c491
        uses: langroodi/doxygenize@v1.6
        with:
          # Doxygen configuration file path
          doxygenconf: ./docs/Doxyfile
          # Generated HTML documents output folder
          htmloutput: ./docs/
          # GitHub Pages branch name
          ghpagesbranch: master
          # GitHub Pages directory path
          ghpagesdir: ./docs/

