# This is a basic workflow to help you get started with Actions

name: Doxygen-Auto-Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      
      - name: Doxygen Action
  # You may pin to the exact commit or the version.
  # uses: mattnotmitt/doxygen-action@9039b4cfaf5097b76489c53c0cdc8cba59091b57
        uses: mattnotmitt/doxygen-action@1.9.1
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxyfile
          # Working directory
          working-directory: ./docs/
          # Generate latex documentation
